version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - ./install_wordpress.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
     restart: always
     env_file: .env

   wordpress:
     build: ./my-wordpress
     depends_on:
       - db
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
     env_file: .env
     volumes:
       - ./themes/sage:/var/www/html/wp-content/themes/sage
volumes:
    db_data:
