version: "2"
services:
    wordpress:
        build: ./my-wordpress
        ports:
            - "9000:80"
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: "db:3306"
        env_file: .env
        volumes:
            - ./themes/sage:/var/www/html/wp-content/themes/sage
    db:
        image: mysql:latest
        env_file: .env
        volumes:
            - "db-data:/var/lib/mysql"
            - "./install_wordpress.sql:/docker-entrypoint-initdb.d/install_wordpress.sql"

# databaseのように永続的なストレージが欲しい場合に必要な設定
# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
volumes:
    db-data:
        driver: local
