language: php

sudo: false

php:
  - "5.6"

env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
    - GIT_COMMITTER_EMAIL=chibataku0815@gmail.com
    - GIT_AUTHOR_NAME=travis-ci
    - GIT_AUTHOR_EMAIL=chibataku0815@gmail.com
    - secure: "y2YHUoejhYxgaqzwFfThAPUgEKLExYpJK21r0xh5cJ+DoEP3pbJVha2f07Q952q1kciEKkYN53zhFMIjiayyDNhG2U3+I0h8KxzGttUcOz2PQNY5uMgvWL4VEOa+wV/VIbEWblZ4Zv0cKQBCwp+vmNtJhJ+PqfkSvSO3dRpobargfxt8R1wYT6mUBmD5XKZpqilOm6/ix0r88iYZy+fXi370ugSW9qzDG9hQVu1C1h06W7v2SbiiKYyU6RrALKUGVsuEFSjC+VmoOeGqDO8jO15Ltl090oP54qfxVxbaD4P3x7z1xMNrhs9CBfAl2ktuQT+QL59fZXvwKMF2u926qWCG8kJ9uHtCOHWFW0m4+8z5+BEvDNEBi86RRHPVCS2pfZnD9vxvSL+Y49vCCAlQs14jIEC143Ywrkc8yxYBjJG7wD0IZUQsTji9l+jMuUdsBwuzNBdn9hgOWwCPP0J0fQCCkqEvgX2dE7qInw7TTBj3RIu/Cgwvcsxik2fP35n1m6RXVDaZVeivzZAhyb0NuNWESkVmJzJrHJUuwmVMoaX7V74Y0zyoE+8ydSQz6fsxoAu7a14q5lPeHSPaAeOTwJRzGCp+jNGSp6Sr0DOOsUcSR9VJyqIkGXe23u5BpGWEWbHBR1ibk/8EVUsoZrFx0iVb4maZzuZGUYp7uzrEUfk="

before_script:
  - nvm install 4.2
  - npm install

script:
  # Search for PHP syntax errors.
  - find . \( -name '*.php' \) -exec php -lf {} \;

after_success:
  # Run npm build task.
  - run npm dist

after_success:
  - bash ./bin/deploy.sh
